### ISSUE TITLE
Simplify File Size Readouts

### ISSUE THREAD

**Issue by rDarge** [The-Dev-Effect/reliquery-ui#48]
It would be nice to simplify the filesizes using decorators or some such, ex 

![image](https://user-images.githubusercontent.com/1133811/144126024-72954d51-ad43-411d-8cda-49f4e90e46b9.png)
(src: https://meta.deveffect.io/dashboard/reliquery/demo/neuromatch/notebook)

could instead be 87.5 MB. 

This would make it easier to understand at a glance what you're considering downloading

**Comment by AntiAnt** [comment]
This will have to be done in reliquery I'll open an issue there and close this one
