### ISSUE TITLE
Remove "brand" from main menu.

### ISSUE THREAD

**Issue by ibebrett** [The-Dev-Effect/reliquery-ui#49]
# Reliquery-UI Issue Report
Thank you for raising our awareness of an Issue with Reliquery-UI. Before submitting this Issue report check and make sure there aren't any duplicate Issues currently open. Please give as much detail about the issue as you can to help us try and resolve it.

## Prerequisites

- [x] Are you running the latest version?

## Description of Issue

Currently there is the word "brand" on the hero card for each item "relics" "storages" "relic types"

Go here:
https://meta.deveffect.io/dashboard 

![rq_brand](https://user-images.githubusercontent.com/219042/144130818-86b46744-d4bb-46fd-9454-7dfcfaa22391.png)

## Expected Behavior

Not to have brand

## Actual Behavior

It has brand

## Steps to Reproduce the Problem
Go here:
https://meta.deveffect.io/dashboard 

## Possible Solution

Remove brand from the code.

**Comment by AntiAnt** [comment]
missed that I will get right on it
